<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="MessagePackAnalyzer" Version="3.1.4" />
    <PackageReference Include="nunit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
      <ProjectReference Include="..\..\..\Core.csproj" />
  </ItemGroup>

</Project>
